on:
  release:
    types:
      - released

name: Nexus Release Announcement

jobs:
  nexus-release-announcement:
    permissions:
      contents: read
    uses: ./.github/workflows/release-announcement.yml
    secrets: inherit