on:
  workflow_call:
    inputs:
      repo-banner-url:
        description: repository banner image url
        type: string
        required: false
        default: "https://github.com/${{ github.repository }}/tree/master/.github/banner.png"
      repo-avatar-url:
        description: repository avatar iamge url
        type: string
        required: false
        default: "https://github.com/${{ github.repository }}/tree/master/.github/avatar.png"      

name: Release Announcement

jobs:
  release-announcement-discord:
    permissions:
      contents: read
    uses: ./.github/workflows/release-announcement-discord.yml
    secrets: inherit
    with:
      thumbnail-url: "${{ inputs.repo-banner-url }}"
      image-url: "${{ inputs.repo-avatar-url }}"
